ALTER TABLE `notices` ADD `title_zh` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_ja` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_ko` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_vi` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_th` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_id` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_ms` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_ru` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_ar` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_es` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_pt` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_fr` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_de` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_it` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_tr` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_hi` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_pl` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_nl` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_uk` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `title_tl` varchar(200);--> statement-breakpoint
ALTER TABLE `notices` ADD `content_zh` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_ja` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_ko` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_vi` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_th` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_id` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_ms` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_ru` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_ar` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_es` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_pt` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_fr` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_de` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_it` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_tr` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_hi` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_pl` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_nl` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_uk` text;--> statement-breakpoint
ALTER TABLE `notices` ADD `content_tl` text;