CREATE TABLE `faqs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`question` text NOT NULL,
	`answer` text NOT NULL,
	`category` varchar(50) DEFAULT 'general',
	`sortOrder` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`question_zh` text,
	`answer_zh` text,
	`question_ja` text,
	`answer_ja` text,
	`question_ko` text,
	`answer_ko` text,
	`question_vi` text,
	`answer_vi` text,
	`question_th` text,
	`answer_th` text,
	`question_id` text,
	`answer_id` text,
	`question_ms` text,
	`answer_ms` text,
	`question_ru` text,
	`answer_ru` text,
	`question_ar` text,
	`answer_ar` text,
	`question_es` text,
	`answer_es` text,
	`question_pt` text,
	`answer_pt` text,
	`question_fr` text,
	`answer_fr` text,
	`question_de` text,
	`answer_de` text,
	`question_it` text,
	`answer_it` text,
	`question_tr` text,
	`answer_tr` text,
	`question_hi` text,
	`answer_hi` text,
	`question_pl` text,
	`answer_pl` text,
	`question_nl` text,
	`answer_nl` text,
	`question_uk` text,
	`answer_uk` text,
	`question_tl` text,
	`answer_tl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `faqs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `qnaQuestions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`nickname` varchar(50),
	`isPrivate` boolean NOT NULL DEFAULT false,
	`category` varchar(50) DEFAULT 'general',
	`question` text NOT NULL,
	`answer` text,
	`answeredBy` int,
	`answeredAt` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`question_zh` text,
	`answer_zh` text,
	`question_ja` text,
	`answer_ja` text,
	`question_ko` text,
	`answer_ko` text,
	`question_vi` text,
	`answer_vi` text,
	`question_th` text,
	`answer_th` text,
	`question_id` text,
	`answer_id` text,
	`question_ms` text,
	`answer_ms` text,
	`question_ru` text,
	`answer_ru` text,
	`question_ar` text,
	`answer_ar` text,
	`question_es` text,
	`answer_es` text,
	`question_pt` text,
	`answer_pt` text,
	`question_fr` text,
	`answer_fr` text,
	`question_de` text,
	`answer_de` text,
	`question_it` text,
	`answer_it` text,
	`question_tr` text,
	`answer_tr` text,
	`question_hi` text,
	`answer_hi` text,
	`question_pl` text,
	`answer_pl` text,
	`question_nl` text,
	`answer_nl` text,
	`question_uk` text,
	`answer_uk` text,
	`question_tl` text,
	`answer_tl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `qnaQuestions_id` PRIMARY KEY(`id`)
);
